on: [push]

jobs:
    build:
        env:
            PLATFORM: foobar

        steps:
        - uses: ilammy/msvc-dev-cmd@v1.1.7
        - name Test
          shell: bash -l {0}
          run: |
            echo $PLATFORM
