on: [push]

jobs:
    build:
        runs-on: 'windows-latest'
        env:
            PLATFORM: foobar

        steps:
        - uses: ilammy/msvc-dev-cmd@v1.8.0
        - name: Test2
          shell: bash -l {0}
          run: |
            echo $PLATFORM
